#!/usr/local/bin/perl

use DBI;
use CGI;

$cgi = new CGI;

print $cgi->header(-type => 'text/plain');

$dbhost = $cgi->server_name();
$dbport = $ENV{'MYSQL_TCP_PORT'};

$debug = $cgi->param('debug');
$organism = $cgi->param('organism');
$showfiles = $cgi->param('show');

unless ($organism) {
    print "! NO ORGANISM SPECIFIED\n";
    exit(0);
}

if ($showfiles) {
    foreach $extn (split(/,/, $showfiles)) {
	$filelist{$extn} = 1;
    }
} 

$organism = lc($organism);

$dsn = 'DBI:mysql:minerva;host=' . $dbhost . ';port=' . $dbport;

$dbh = DBI->connect($dsn, 'minerva', 'daughter of Jupiter');

&db_die('Unable to connect to ' . $dsn) unless $dbh;

print "# DSN $dsn\n" if $debug;

$query = 'SELECT assemblydir,splitdir FROM repository WHERE organism=' . $dbh->quote($organism);

print "# QUERY $query\n" if $debug;

$sth = $dbh->prepare($query);
&db_die("prepare($query) failed");

$sth->execute();
&db_die("execute($query) failed");

while (@ary = $sth->fetchrow_array()) {
    ($asmdir, $splitdir) = @ary;
    print "# ORGANISM $organism\n#   ASSEMBLY-DIR $asmdir\n#   SPLIT-DIR $splitdir\n" if $debug;
}

$dbh->disconnect();

unless (defined($asmdir)) {
    print "!The project named $organism does not exist\n";
    exit(0);
}

$analysisdir = $asmdir . '/Analysis';

print "# ANALYSIS-DIR $analysisdir\n" if $debug; 

unless (opendir(DIR, $analysisdir)) {
    print "!Unable to open directory $analysisdir\n";
    exit(0);
}

while ($fname = readdir(DIR)) {
    next if ($fname =~ /^\./);
    ($stem, $extn, $junk) = split(/\./, $fname);

    next unless ($stem eq $organism);

    $fullname = "$analysisdir/$fname";

    if ($showfiles) {
	next unless defined($filelist{$extn});
	if (open(INFILE, $fullname)) {
	    print ">>>> $extn $fullname <<<<\n";
	    while (<INFILE>) {
		print;
	    }
	} else {
	    print "!Unable to open $fullname for reading\n";
	}
    } else {
	print $fullname,"\n" if -f $fullname;
    }
}

closedir(DIR);

exit(0);

sub db_die {
    my $msg = shift;
    return unless $DBI::err;
    print "MySQL error: $msg: $DBI::err ($DBI::errstr)\n\n";
    exit(0);
}
