#!/usr/local/bin/perl

use DBI;
use CGI;

$cgi = new CGI;

print $cgi->header(-type => 'text/plain');

$dbhost = $cgi->server_name();
$dbport = $ENV{'MYSQL_TCP_PORT'};

$debug = $cgi->param('debug');
$organism = $cgi->param('organism');

unless ($organism) {
    print "! NO ORGANISM SPECIFIED\n";
    exit(0);
}

$organism = uc($organism);

$dsn = 'DBI:mysql:minerva;host=' . $dbhost . ';port=' . $dbport;

$dbh = DBI->connect($dsn, 'minerva', 'daughter of Jupiter');

&db_die('Unable to connect to ' . $dsn) unless $dbh;

print "# DSN $dsn\n" if $debug;

$query = 'SELECT assemblydir,splitdir FROM repository WHERE organism=' . $dbh->quote($organism);

print "# QUERY $query\n" if $debug;

$sth = $dbh->prepare($query);
&db_die("prepare($query) failed");

$sth->execute();
&db_die("execute($query) failed");

while (@ary = $sth->fetchrow_array()) {
    ($asmdir, $splitdir) = @ary;
    print "# $organism\t$asmdir\t$splitdir\n" if $debug;
}

$dbh->disconnect();

unless (defined($splitdir)) {
    print "!The project named $organism does not exist\n";
    exit(0);
}

unless (opendir(DIR, $splitdir)) {
    print "!Unable to open directory $splitdir\n";
    exit(0);
}

while ($fname = readdir(DIR)) {
    next if ($fname =~ /^\./);
    next unless ($fname =~ /^($organism|BIN)/);

    $fullname = "$splitdir/$fname";

    print $fullname,"\n" if -d $fullname;
}

closedir(DIR);

exit(0);

sub db_die {
    my $msg = shift;
    return unless $DBI::err;
    print "MySQL error: $msg: $DBI::err ($DBI::errstr)\n\n";
    exit(0);
}
