#!/usr/local/bin/perl

use DBI;

$db = shift;

die "Usage: analyseDBs host:port" unless $db;

($dbhost, $dbport) = split(/:/, $db);

die "Usage: analyseDBs host:port" unless (defined($dbhost) && defined($dbport));

$dsn = 'DBI:mysql:arcturus;host=' . $dbhost . ';port=' . $dbport;

$dbh = DBI->connect($dsn, 'arcturus', '***REMOVED***',
		    {PrintError => 0, RaiseError => 0});

&db_die("Unable to connect to $dsn") unless $dbh;

$query = 'SHOW DATABASES';

$sth = $dbh->prepare($query);
&db_die("prepare($query) failed on $dsn");

$sth->execute();
&db_die("execute($query) failed on $dsn");

while(@ary = $sth->fetchrow_array()) {
    ($dbname, $junk) = @ary;
    push @databases, $dbname;
}

$sth->finish();

foreach $dbname (@databases) {
    $query = "SELECT * FROM $dbname.READS WHERE 1=0";

    $sth = $dbh->prepare($query);
    &db_die("prepare($query) failed on $dsn");

    $sth->execute();
    if ($DBI::err == 1146) {
	print "Database $dbname has no table named READS\n";
    } elsif ($DBJ::err == 0) {
	print "Database $dbname: OK\n";
    } else {
	&db_die("execute($query) failed on $dsn");
    }

    $sth->finish();
}

$dbh->disconnect();

exit(0);

sub db_die {
    my $msg = shift;
    return unless $DBI::err;
    print STDERR "MySQL error: $msg $DBI::err ($DBI::errstr)\n\n";
    exit(0);
}
