#!/bin/csh

set wrapper=../shared/perlWrapper.lsf

if ( ! -f $wrapper ) then
    echo The LSF wrapper script $wrapper does not exist
    exit 1
endif

foreach perlscript (*.pl)
    set target=$perlscript:r.lsf

    if ( -e $target && ! -l $target ) then
        echo $target already exists and is not a symbolic link
    else
        echo Creating wrapper for $perlscript

        ln -s -f $wrapper $target
    endif
end
