create synonym ARCHIVED_DATA for TRACKING.ARCHIVED_DATA;

create synonym DISK_PARTITION for TRACKING.DISK_PARTITION;

create synonym UNIX_ACCOUNT for TRACKING.UNIX_ACCOUNT;

create synonym REPOSITORYTYPEDICT for TRACKING.REPOSITORYTYPEDICT;

create synonym ONLINE_STATUS for TRACKING.ONLINE_STATUS;

create synonym ONLINESTATUSDICT for TRACKING.ONLINESTATUSDICT;
