#!/bin/bash

SCRIPT_HOME=`dirname $0`
SCRIPT_NAME=`basename $0`

PERL_SCRIPT_NAME=${SCRIPT_HOME}/${SCRIPT_NAME}.pl

PERL_LIB_DIR=${SCRIPT_HOME}/../lib

if [ "x$PERL5LIB" != "x" ]
then
  export PERL5LIB=${PERL_LIB_DIR}:${PERL5LIB}
else
  export PERL5LIB=${PERL_LIB_DIR}
fi

if [ -x ${PERL_SCRIPT_NAME} ]
then
    exec ${PERL_SCRIPT_NAME} "$@"
else
    echo Error: ${PERL_SCRIPT_NAME} is not a valid command
fi
