#!/bin/csh -f

set basedir=`dirname $0`

setenv JAVA_HOME /software/jdk1.6.0_01

set JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false"
  
if ( $?JAVA_OPTS ) then
  setenv JAVA_OPTS "${JAVA_OPTS} ${JMX_OPTS}"
else
  setenv JAVA_OPTS "${JMX_OPTS}"
endif

source ${basedir}/setup.csh

set ARCTURUS_HOME=/nfs/users/nfs_k/kt6/ARCTURUS/arcturus/branches/import-export/java/scripts
set ARCTURUS_JAR=${ARCTURUS_HOME}/../arcturus.jar
echo Overriding Arcturus JAR file and using $ARCTURUS_JAR in version $ARCTURUS_HOME

${JAVA_HOME}/bin/java ${JAVA_OPTS} -jar ${ARCTURUS_JAR} $*
