package uk.ac.sanger.arcturus.jdbc;

import java.lang.management.ManagementFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import javax.management.MBeanServer;
import javax.management.MalformedObjectNameException;
import javax.management.ObjectName;

import uk.ac.sanger.arcturus.Arcturus;
import uk.ac.sanger.arcturus.database.ArcturusDatabase;
import uk.ac.sanger.arcturus.database.ArcturusDatabaseException;

public abstract class AbstractManager implements AbstractManagerMBean {
	protected ArcturusDatabase adb;
	protected boolean cacheing = true;
	protected Connection conn;
	protected boolean savedAutoCommit;
	protected ObjectName mbeanName = null;
	
	private static int instanceCounter = 0;
	
	protected AbstractManager(ArcturusDatabase adb) {
		this.adb = adb;
		
		if (adb instanceof ArcturusDatabaseImpl)
			((ArcturusDatabaseImpl)adb).addManager(this);
		
		registerAsMBean();
	}
	
	protected void registerAsMBean() {
		try {
			mbeanName = new ObjectName("AbstractManager:" + getName());
		} catch (MalformedObjectNameException e) {
			Arcturus.logWarning("Failed to create ObjectName", e);
		}
		
		MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
		
		try {
			mbs.registerMBean(this, mbeanName);
		} catch (Exception e) {
			Arcturus.logWarning("Failed to register connection pool as MBean", e);
		}
	}
	
	private String getName() {
		int serial = instanceCounter++;
		
		String[] classNameParts = getClass().getName().split("\\.");
		
		String className = classNameParts[classNameParts.length - 1];
		
		return "type=" + className + ",serial=" + serial;
	}
	
	public void close() {
		unregisterAsMBean();
	}
		
	protected void unregisterAsMBean() {
		if (mbeanName != null) {
			MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
			
			try {
				mbs.unregisterMBean(mbeanName);
				mbeanName = null;
			} catch (Exception e) {
				Arcturus.logWarning("Failed to unregister connection pool as MBean", e);
			}
		}
	}
	
	public abstract String getCacheStatistics();

	public void setCacheing(boolean cacheing) {
		this.cacheing = cacheing;
	}

	public boolean isCacheing() {
		return cacheing;
	}

	public abstract void clearCache();
	
	public abstract void preload() throws ArcturusDatabaseException;
	
	protected abstract void prepareConnection() throws SQLException;
	
	protected PreparedStatement prepareStatement(String query) throws SQLException {
		return prepareStatement(query, Statement.NO_GENERATED_KEYS);
	}
	
	protected PreparedStatement prepareStatement(String query, int autoGeneratedKeys) throws SQLException {
		if (conn == null)
			throw new SQLException("Cannot prepare a statement on a null connection");
		
		try {
			return conn.prepareStatement(query, autoGeneratedKeys);
		}
		catch (SQLException e) {
			throw new SQLException("Failed to prepare statement \"" + query + "\"", e);
		}
	}

	protected void setConnection(Connection conn) throws SQLException {
		this.conn = conn;		
		prepareConnection();
	}
	
	protected Connection getConnection() {
		return conn;
	}
	
	protected void beginTransaction() throws SQLException {
		savedAutoCommit = conn.getAutoCommit();
		conn.setAutoCommit(false);
	}
	
	protected void commitTransaction() throws SQLException {
		conn.commit();
		conn.setAutoCommit(savedAutoCommit);
	}
	
	protected void rollbackTransaction() throws SQLException {
		conn.rollback();
		conn.setAutoCommit(savedAutoCommit);
	}
}
