#!/usr/local/bin/perl -w

#############################################################################
# get assembly data for  Cyclops from ARCTURUS database
#############################################################################

use strict; # Constraint variables declaration before using them

use GateKeeper; 

##############################################################################
# unbuffered output
##############################################################################

open(STDERR,">&STDOUT") || die "Can't dump to STDOUT: $!\n";
select(STDERR); $| = 1; # Make unbuffered.
select(STDOUT); $| = 1; # Make unbuffered.

##############################################################################
# get configuration data, open CGI and MySQL Database
##############################################################################

my $GateKeeper = GateKeeper->new('mysql',0);

my $config     = $GateKeeper->configHandle();

my $cgi        = $GateKeeper->cgiHandle();

my $database   = $cgi->parameter('database') || 'arcturus';

my $organisms  = $GateKeeper->dbHandle($database,{returnTableHandle => 1});

$GateKeeper->cgiHeader(2);

##############################################################################
# MAIN
##############################################################################

my $status = $GateKeeper->authorize(0,{'nosession'=>0, silently=>1, ageWindow=>300});

my $page = $GateKeeper->GUI("Keeper TEST setup");
    $page->form(0);
    $page->flush;
    $GateKeeper->disconnect;
exit 0;

if (!$status) {
    my $error = $GateKeeper->{error};
    $GateKeeper->report($error);
}
else {
    $GateKeeper->report("Accepted");

    my $page = $cgi->openPage("Now the follow up");
    $page->form("/cgi-bin/test/keeper");
    $page->sectionheader("Submit form to test transfer of session number",4,1);
    $page->add($page->ShortList());
    $page->ingestCGI();
    $page->submitbuttonbar();
    $page->form(0);
    $page->flush;
    $GateKeeper->disconnect;
}

##############################################################################
# EXIT
##############################################################################

$GateKeeper->disconnect();

exit 0;
