#!/usr/local/bin/perl -w

#############################################################################
# get assembly data for  Cyclops from ARCTURUS database
#############################################################################

use strict; # Constraint variables declaration before using them

use lib "/nfs/pathsoft/arcturus/dev/lib";

use GateKeeper; 
use ArcturusTable;

##############################################################################
# unbuffered output
##############################################################################

open(STDERR,">&STDOUT") || die "Can't dump to STDOUT: $!\n";
select(STDERR); $| = 1; # Make unbuffered.
select(STDOUT); $| = 1; # Make unbuffered.

##############################################################################
# get configuration data, open CGI and MySQL Database
##############################################################################

my $GateKeeper = GateKeeper->new('mysql',0);

my $config     = $GateKeeper->configHandle();

my $cgi        = $GateKeeper->cgiHandle();

my $database   = $cgi->parameter('database') || 'arcturus';

# my $dbh        = $GateKeeper->dbHandle($database);

$GateKeeper->cgiHeader(2);

##############################################################################
# MAIN
##############################################################################

# my $identify = 'ejz';
# my $password = 'blbla';
# undef $password;

my $status = $GateKeeper->authorize(100,{'nosession'=>0, silently=>0, ageWindow=>300});

if (!$status) {
    my $error = $GateKeeper->{error};
    $GateKeeper->report($error);
}
else {
    $GateKeeper->report("Accepted");

    my $page = $cgi->openPage("Now the follow up");
    $page->form("/cgi-bin/test/keeper");
    $page->sectionheader("Submit form to test transfer of session number",4,1);
    $page->add($page->ShortList());
    $page->ingestCGI();
    $page->submitbuttonbar();
    $page->form(0);
    $page->flush;
    $GateKeeper->disconnect;
}




##############################################################################
# EXIT
##############################################################################

$GateKeeper->disconnect();
