#!/usr/local/bin/perl

use DBI;
use Term::ReadKey;
use Digest::MD5 qw(md5_hex);
use Compress;

$compressor = new Compress('ACGT- ');

while ($nextword = shift @ARGV) {
    $dba = shift @ARGV if ($nextword eq '-dba');
    $dbb = shift @ARGV if ($nextword eq '-dbb');

    $mysqluser = shift @ARGV if ($nextword eq '-user');

    $mysqlpass = shift @ARGV if ($nextword eq '-pass');

    $dodna = 1 if ($nextword eq '-dodna');

    $doquality = 1 if ($nextword eq '-doquality');

    $limit = shift @ARGV if ($nextword eq '-limit');

    $byname = 1 if ($nextword eq '-byname');

    $namelike = shift @ARGV if ($nextword eq '-namelike');

    if ($nextword eq '-help') {
	&showUsage();
	exit(0);
    }
}

$byname = 0 unless defined($byname);

$dodna = 0 unless defined($dodna);
$doquality = 0 unless defined($doquality);

unless ($dodna || $doquality) {
    $dodna = 1;
    $doquality = 1;
}

unless (defined($dba) && defined($dbb) && defined($mysqluser)) {
    &showUsage();
    exit(0);
}

unless (defined($mysqlpass)) {
    print STDERR "Enter MySQL password for $mysqluser\n";
    ReadMode 'noecho';
    $mysqlpass = ReadLine 0;
    ReadMode 'normal';
    chop $mysqlpass;
}

($hosta,$porta,$dbnamea) = $dba =~ /(\w+):(\w+)\/(\w+)/;

die "-dba parameter is not in correct format"
    unless (defined($hosta) && defined($porta) && defined($dbnamea));

($hostb,$portb,$dbnameb) = $dbb =~ /(\w+):(\w+)\/(\w+)/;

die "-dbb parameter is not in correct format"
    unless (defined($hostb) && defined($portb) && defined($dbnameb));

$dsna = 'DBI:mysql:' . $dbnamea . ';host=' . $hosta . ';port=' . $porta;

$dbha = DBI->connect($dsna, $mysqluser, $mysqlpass,
		     {PrintError => 0, RaiseError => 0});

&db_die("Unable to connect to $dsna") unless $dbha;

$dsnb = 'DBI:mysql:' . $dbnameb . ';host=' . $hostb . ';port=' . $portb;

$dbhb = DBI->connect($dsnb, $mysqluser, $mysqlpass,
		     {PrintError => 0, RaiseError => 0});

&db_die("Unable to connect to $dsnb") unless $dbhb;

$dnaselect = $dodna ? ', sequence, scompress' : '';
$qualityselect = $doquality ? ', quality, qcompress' : '';

$lockquery = 'LOCK TABLES READS READ';

print STDERR "Trying to lock READS table on $dsna ...\n";

$dbha->do($lockquery);
&db_die("do($lockquery) failed on $dsna");

print STDERR "Trying to lock READS table on $dsnb ...\n";

$dbhb->do($lockquery);
&db_die("do($lockquery) failed on $dsnb");

$querya = "SELECT read_id, readname, slength $dnaselect $qualityselect from READS";

$querya .= " WHERE readname like '$namelike'" if defined($namelike);

$querya .= " LIMIT $limit" if defined($limit);

print STDERR "Preparing \"$querya\" on $dsna ...\n";

$stha = $dbha->prepare($querya);
&db_die("prepare($querya) failed on $dsna");

$tomatch = $byname ? 'readname' : 'read_id';

$queryb = "SELECT read_id, readname, slength $dnaselect $qualityselect from READS where $tomatch=?";

print STDERR "Preparing \"$queryb\" on $dsnb ...\n";

$sthb = $dbhb->prepare($queryb);
&db_die("prepare($queryb) failed on $dsnb");

$nreads = 0;
printf STDERR "%8d", $nreads;
$format = "\010\010\010\010\010\010\010\010%8d";

$stha->execute();
&db_die("execute($querya) failed on $dsna");

$nmatched = 0;

while (@arya = $stha->fetchrow_array()) {
    $read_id = shift @arya;
    $readnamea = shift @arya;
    $slengtha = shift @arya;

    if ($dodna) {
	$seqa = shift @arya;
	$method = shift @arya;
	($slena, $seqa) = $compressor->sequenceDecoder($seqa, $method) if ($method > 0);
    }

    if ($doquality) {
	$quala = shift @arya;
	$method = shift @arya;
	($qlen, $quala) = $compressor->qualityDecoder($quala, $method) if ($method > 0);
	$quala =~ s/^\s+|\s+$//;
	$quala = pack("c*", split(/\s+/, $quala));
	$qualalen = length($quala);
	$qualahash = md5_hex($quala);
    }

    if ($byname) {
	$sthb->execute($readnamea);
    } else {
	$sthb->execute($read_id);
    }

    $nmatchb = 0;

    while (@aryb = $sthb->fetchrow_array()) {
	$read_idb = shift @aryb;
	$readnameb = shift @aryb;

	if (!$byname) {
	    print "$read_id: readname mismatch: $readnamea vs $readnameb\n"
		if ($readnamea ne $readnameb);
	}

	$uniqueid = $byname ? $readnamea : $read_id;

	$slengthb = shift @aryb;

	print "$uniqueid: slength mismatch: $slengtha vs $slengthb\n"
	    if ($slengtha != $slengthb);

	if ($dodna) {
	    $seqb = shift @aryb;
	    $method = shift @aryb;
	    ($slenb, $seqb) = $compressor->sequenceDecoder($seqb, $method) if ($method > 0);

	    print "$uniqueid: sequence mismatch\n" if ($seqa != $seqb);
	}

	if ($doquality) {
	    $qualb = shift @aryb;
	    $method = shift @aryb;
	    ($qlen, $qualb) = $compressor->qualityDecoder($qualb, $method) if ($method > 0);
	    $qualb =~ s/^\s+|\s+$//;
	    $qualb = pack("c*", split(/\s+/, $qualb));
	    $qualblen = length($qualb);

	    if ($qualalen == $qualblen) {
		$qualbhash = md5_hex($qualb);
		print "$uniqueid: base quality mismatch\n" if ($qualahash ne $qualbhash);
	    } else {
		print "$uniqueid: base quality length mismatch: $qualalen vs $qualblen\n";
	    }

	}

	$nmatchb++;
    }

    $nmatched++ if ($nmatchb > 0);

    $nreads++;
    printf STDERR $format, $nreads if (($nreads % 50) == 0);
}

printf STDERR $format, $nreads;
print STDERR " reads found ... done.\n";

if ($nmatched < $nreads) {
    print STDERR "*** Only found matches for $nmatched reads from $dba\n";
}

$stha->finish();
$sthb->finish();

$unlockquery = 'UNLOCK TABLES';

$dbha->do($unlockquery);
$dbhb->do($unlockquery);

$dbha->disconnect();
$dbhb->disconnect();

exit(0);

sub db_die {
    my $msg = shift;
    return unless $DBI::err;
    print STDERR "MySQL error: $msg $DBI::err ($DBI::errstr)\n\n";
    exit(0);
}

sub showUsage {
    print STDERR "MANDATORY PARAMETERS:\n";
    print STDERR "    -dba\t\tFirst database (as host:port/database)\n";
    print STDERR "    -dbb\t\tSecond database (as host:port/database)\n";
    print STDERR "    -user\t\tMySQL username\n";
    print STDERR "\n";
    print STDERR "MODE CONTROL OPTIONS:\n";
    print STDERR "    -dodna\t\tCompare DNA sequence data\n";
    print STDERR "    -doquality\t\tCompare base quality data\n";
    print STDERR "\n";
    print STDERR "OPTIONAL PARAMETERS:\n";
    print STDERR "    -pass\t\tMySQL password (you will be prompted for one if absent)\n";
    print STDERR "    -limit\t\tSpecify the maximum number of reads to compare\n";
    print STDERR "    -byname\t\tCompare reads by name instead of read_id\n";
    print STDERR "    -namelike\t\tSelect readnames like this from first database\n";
}
