#!/usr/local/bin/perl

use strict;

use WrapDBI;
use DBI;

my $njobs = 8;
my $instance = 'dev';
my $organism;
my $schema;
my $projid = 1;
my $queue;

while (my $nextword = shift @ARGV) {
    $njobs = shift @ARGV if ($nextword eq '-njobs');

    $instance = shift @ARGV if ($nextword eq '-instance');

    $organism = shift @ARGV if ($nextword eq '-organism');

    $schema = shift @ARGV if ($nextword eq '-schema');

    $projid = shift @ARGV if ($nextword eq '-projid');

    $queue = shift @ARGV if ($nextword eq '-q');
}

unless (defined($organism) && defined($schema) && defined($queue)) {
    &showUsage();
    exit(1);
}

my $dbh = WrapDBI->connect('pathlook');

die "Unable to establish connection to Oracle" unless defined($dbh);

my $query = "select readid from $schema.EXTENDED_READ where projid=$projid and processstatus='PASS' order by readid asc";

my $sth = $dbh->prepare($query);

if ($DBI::err) {
    print "Error in prepare: $DBI::errstr\n";
    exit(0);
}

$sth->execute();

my @readids;

while (my ($readid) = $sth->fetchrow_array()) {
    push @readids, $readid;
}

$sth->finish();

$dbh->disconnect();

my @headers =
    ('#!/bin/csh -f',
     '',
     'set SCRIPT_HOME=`dirname $0`',
     'set UTILS_DIR=${SCRIPT_HOME}/../utils',
     '',
     'set bsub="bsub"',
     'set script=${UTILS_DIR}/readloader',
     'set params="-instance ' . $instance . ' -organism ' . $organism . ' -source Oracle -schema ' . $schema . ' -projid ' . $projid . '"',
     'set queue="-q ' . $queue . '"'
     );

foreach my $line (@headers) {
    print "$line\n";
}

my $nreads = scalar(@readids);

my $nblock = int($nreads/$njobs);

for (my $job = 0; $job < $njobs; $job++) {
    my $nstart = $job * $nblock;
    my $nfinish = ($job + 1) * $nblock - 1;

    print '${bsub} ${queue} ${script} ${params}';

    if ($job > 0) {
	print " -minreadid ",$readids[$nstart];
    }

    if ($job < $njobs - 1) {
	print " -maxreadid ",$readids[$nfinish];
    }

    print "\n";
}

exit(0);

sub showUsage {
    print STDERR "MANDATORY PARAMETERS:\n";
    print STDERR "\t-organism\t\tArcturus organism name\n";
    print STDERR "\t-schema\t\t\tOracle schema name\n";
    print STDERR "\t-q\t\t\tBatch queue name\n";

    print STDERR "\nOPTIONAL PARAMETERS:\n";
    print STDERR "\t-njobs\t\t\tNumber of parallel jobs [default: 8]\n";
    print STDERR "\t-instance\t\tArcturus instance [default: dev]\n";
    print STDERR "\t-projid\t\t\tOracle project ID [default: 1]\n";
}
