#!/usr/local/bin/perl

$babelroot = '/nfs/pathdb/arcturus/mysql/binlog';
$pcs3root  = '/nfs/pathdb2/arcturus/mysql/binlog';

&binlogStats('babel', $babelroot);
print "\n";
&binlogStats('pcs3',  $pcs3root);

exit(0);

sub binlogStats {
    my $cluster = shift;
    my $rootdir = shift;

    die "No cluster name specified" unless $cluster;
    die "No root directory namespecified" unless $rootdir;

    die "Unable to opendir($rootdir)" unless opendir(DIR, $rootdir);

    my $filename;

    my @allfiles = readdir(DIR);

    closedir(DIR);

    foreach $filename (@allfiles) {
	next unless ($filename =~ /^[a-z]+/);
	my $fullname = "$rootdir/$filename";
	next unless -d $fullname;

	die "Unable to opendir($fullname)" unless opendir(SUBDIR, $fullname);

	my $nfiles = 0;
	my $nbytes = 0;

	my $subfile;

	my @allsubfiles = readdir(SUBDIR);

	closedir(SUBDIR);

	foreach $subfile (@allsubfiles) {
	    next unless ($subfile =~ /^mysql\.\d+/);
	    my @statdata = stat("$fullname/$subfile");
	    $nfiles += 1;
	    $nbytes += $statdata[7];
	}

	printf "%-10s %-16s  %4d files  %10d bytes\n", $cluster, $filename, $nfiles, $nbytes;
    }
}
