#!/usr/local/bin/perl

use WrapMySQL;

while ($nextword = shift @ARGV) {
    $instance = shift @ARGV if ($nextword eq '-instance');
}

$dbh = WrapMySQL->connect($instance, 'read');

die "Unable to connect to instance $instance" unless $dbh;

$query = 'SHOW DATABASES';

$sth = $dbh->prepare($query);
&db_die("prepare($query) failed on instance $instance");

$sth->execute();
&db_die("execute($query) failed on instance $instance");

while(@ary = $sth->fetchrow_array()) {
    ($dbname, $junk) = @ary;
    push @databases, $dbname;
}

$sth->finish();

foreach $dbname (sort @databases) {
    $query = "SELECT COUNT(*) FROM $dbname.READS2CONTIG WHERE label>9";

    $sth = $dbh->prepare($query);
    &db_die("prepare($query) failed on instance $instance");

    $sth->execute();

    if ($DBJ::err == 0) {
	@ary = $sth->fetchrow_array();
	printf "%-20s %8d\n", $dbname, $ary[0];
    } else {
	&db_die("execute($query) failed on instance $instance") unless ($DBI::err == 1146);
    }

    $sth->finish();
}

$dbh->disconnect();

exit(0);

sub db_die {
    my $msg = shift;
    return unless $DBI::err;
    print STDERR "MySQL error: $msg: $DBI::err ($DBI::errstr)\n\n";
    exit(0);
}
