#!/bin/csh

set wrapper=../shared/perlWrapper

if ( ! -f $wrapper ) then
    echo The Perl wrapper script $wrapper does not exist in this directory
    exit 1
endif

foreach perlscript (*.pl)
    set target=$perlscript:r

    if ( -e $target && ! -l $target ) then
        echo $target already exists and is not a symbolic link
    else
        echo Creating wrapper for $perlscript

        ln -s -f $wrapper $target
    endif
end
