#!/bin/csh -f

set OPLOG=/nfs/pathsoft/arcturus/utils/marmalise.out
set BSUBLOG=/nfs/pathsoft/arcturus/utils/marmalise.bsub
set SCRIPT=/nfs/pathsoft/arcturus/utils/marmaliseDB

touch $OPLOG
touch $BSUBLOG

foreach i (1 2 3 4 5 6 7 8 9 10)
  bsub -o $OPLOG -q pcs3q1 $SCRIPT >> $BSUBLOG
  bsub -o $OPLOG -q babelq1 $SCRIPT >> $BSUBLOG
end
