#!/bin/csh -f

set SCRIPT_HOME=`dirname $0`

set PERL_LIB_DIR=${SCRIPT_HOME}/../lib

setenv PERL5LIB /nfs/pathsoft/external/perl/lib:${PERL_LIB_DIR}:${PERL5LIB}

exec ${SCRIPT_HOME}/read-loader.pl $*
