#!/usr/local/bin/perl 

#############################################################################
#
# ARCTURUS database entrance portal
#
#############################################################################

use strict; # Constraint variables declaration before using them

use GateKeeper; 

##############################################################################
# get configuration data, open CGI and MySQL Database
##############################################################################

my %options = (insistOnCGI=>1 , diagnosticsOn=>0 , dieOnNoTable=>0, writeAccess => 1);

my $GateKeeper = new GateKeeper('mysql',\%options);

my $cgi        = $GateKeeper->cgiHandle(1);

my $database   = $cgi->parameter('database') || 'arcturus';

my $organisms  = $GateKeeper->dbHandle($database,{returnTableHandle => 1});

##############################################################################
# MAIN
##############################################################################

my ($void, $action, $page);

($void, $action) = split ('/',$GateKeeper->origin);

if ($action eq 'signon') {

    $page = $GateKeeper->GUI("Welcome to the assembly-tracking database",{doTransport=>0});
    $GateKeeper->authorize(0,{ageWindow=>180}); # bounce authorization form
}

elsif ($action eq 'signoff') {

    my ($dummy, $session) = split ':',$cgi->parameter('session');

    my $confirm = $GateKeeper->lookup('confirm');

    $cgi->delete('session') if $confirm; # build GUI without
    $page = $GateKeeper->GUI("Sign off",{doTransport=>0});
    $page->space(5);
    if ($confirm) {
# if no-reopen flag set, close the session on the SESSIONS file
        $GateKeeper->closeSession($session,1) if $GateKeeper->lookup('no-reopen');
        $page->add("Your session $session has been closed",0,0,'size=+1');
    } 
    else {
        $page->form($GateKeeper->currentScript.'/signoff');
        $page->add("Current session $session will be closed",0,0,'size=+1');
        $page->space(1);
        my $reopen = "<TABLE><TR><TD><FONT SIZE=+1>Check if session may not be reopened</FONT></TD>";
        $reopen .= "<TD><INPUT TYPE=checkbox NAME=no-reopen></TD></TR></TABLE>";
        $page->add($reopen);
        $page->space(1);
        $page->confirmbuttonbar(0,0);
    }
    $page->ingestCGI;
    $page->flush();
}

else {
# if the script is invoked by the identification prompt: get session number
    my $authorized = 1;
    if ($cgi->parameter('identify')) {
        $authorized = $GateKeeper->authorize(0,{ageWindow=>180}); # (all action except access test)  
    }

    $page = $GateKeeper->GUI("Welcome to the assembly-tracking database");
    $page->space;
    $page->sectionheader("Welcome to the ARCTURUS assembly-tracking database",4,0);

    my $font = "size=4 face='sans-serif'";

    if (!$authorized) {
# after return from 'signon'
            $page->space(2);
            $page->message("! Signon failed: $GateKeeper->{error}",'FFCA88','size = +1');
            $page->space(1);
            $page->message("Please try again",'white','size = +1');
    }
    elsif ($GateKeeper->instance) {
        my $count = $organisms->count();
        my $text = "There are $count Organism databases listed on this server";
        $text =~ s/are/is/ if ($count <= 1);
        $text =~ s/ses/se/ if ($count <= 1);
        $text =~ s/0/no/   if !$count;
        $page->space(1);
        $page->add($text,0,0,$font);
        $page->space(1);

# because the database can have been changed in GUI get it again

        $database   = $cgi->parameter('database') || 'arcturus';

        if ($count && $database ne 'arcturus') {
            my %options = (mask=>'0110000001111000001',
                           headColor=>'FAFAD2',cellColor=>'CCCCCC',linkColor=>'E2E2FF');
            my $table = $organisms->htmlTable(\%options,'dbasename',$database);
            $page->add($table);
# possibly other info
        }
        elsif ($count) {
            my %options = (mask=>'0310000001111000001',linkItem=>'onItemName', linkTarget=>0,
                           headColor=>'FAFAD2',cellColor=>'CCCCCC',linkColor=>'E2E2FF');
            my $table = $organisms->htmlTable(\%options);

            my $thisScript = $GateKeeper->currentScript;
            my $session = $cgi->parameter('session');
            $table =~ s/ITEMLINK\?/ITEMLINK?session=$session&/g if $session;
            $table =~ s/ITEMLINK/$thisScript/g; # replace placeholder
            $table =~ s/dbasename/database/g;
            $page->add($table);
            $page->space;
            $page->sectionheader("Select a database or a function",4,0);
        }
        else {
            $text = "Add an Organism database with the CREATE menu";  
            $page->add($text,0,0,$font);
        }
    }
    else {
        my $server = $GateKeeper->currentServer;
        $page->space(2);
        $page->add("There is NO arcturus instance on this server $server",0,0,$font);
        $page->space(1);
        $page->add("Create a new instance from scratch using the CREATE menu",0,0,$font);
    }

    $page->flush();
}

##############################################################################

$GateKeeper->disconnect;

exit 0;










