#!/usr/local/bin/perl -w

#############################################################################
#
# ?? to be developed ??
#
#############################################################################

use strict; # Constraint variables declaration before using them

use GateKeeper;
use ArcturusTable;
# use TableReader::ReadsRecall;
use MyHTML; # dynamic HTML formatter

##############################################################################
# unbuffered output
##############################################################################

open(STDERR,">&STDOUT") || die "Can't dump to STDOUT: $!\n";
select(STDERR); $| = 1; # Make unbuffered.
select(STDOUT); $| = 1; # Make unbuffered.

##############################################################################
# get configuration data, open CGI and MySQL Database
##############################################################################

my $GateKeeper = new GateKeeper('mysql',0,1); # CGI access only

my $config     = $GateKeeper->configHandle();

my $cgi        = $GateKeeper->cgiHandle();

my ($void,$action,$database,$tablename) = split ('/', $GateKeeper->origin);

my $dbh        = $GateKeeper->dbHandle($database);

$GateKeeper->cgiHeader(1); # return string plain

##############################################################################
# MAIN
##############################################################################

my $USERSUPPORT = $config->get("USERSUPPORT");
my $db_manager  = $config->get("db_manager");    
my $arc_cgi_dir = $config->get("ARC_CGI_DIR");  
my $arc_htm_dir = $config->get("ARC_HTML_DIR");  


my $page = MyHTML->new('ARCTURUS ASSEMBLY-TRACKING DATABASE');
$page->address('ejz@sanger.ac.uk','Ed Zuiderwijk',2);
$page->frameborder(100,15,'white',15);

#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
# open the ORGANISMS table in arcturus
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

my $organisms = ArcturusTable->new($dbh,'ORGANISMS','arcturus',1);
my $loadinfo  = $organisms->unpackAttributes($database);

$page->partition(2);
$page->sectionheader("ARCTURUS assembly tracking database: Contig Manager",3,0);
$page->partition(1);
$page->center(1);

# protect against unintended usage of this script

$page->add($cgi->PrintVariables());
if ($cgi->parameter('database') ne "$database" || $cgi->parameter('tablename') ne $tablename) {
    $page->errorbox("This script is invoked in an invalid manner",0,0,'yellow');
}

$page->flush();
$dbh->disconnect();
exit 0;






