#!/usr/local/bin/perl -w

#############################################################################
# get assembly data for  Cyclops from ARCTURUS database
#############################################################################

use strict; # Constraint variables declaration before using them

# use lib "/nfs/pathsoft/arcturus/dev/lib";

use GateKeeper; 
use ArcturusTable;

##############################################################################
# unbuffered output
##############################################################################

open(STDERR,">&STDOUT") || die "Can't dump to STDOUT: $!\n";
select(STDERR); $| = 1; # Make unbuffered.
select(STDOUT); $| = 1; # Make unbuffered.

##############################################################################
# get configuration data, open CGI and MySQL Database
##############################################################################

my $GateKeeper = GateKeeper->new('mysql');

my $config     = $GateKeeper->configHandle();

my $cgi        = $GateKeeper->cgiHandle();

$GateKeeper->cgiHeader(1); # return string plain

my $instances  = $config->get('mysql_ports');

##############################################################################
# connect to all instances 
##############################################################################

undef my %handles;

my $report;
foreach my $instance (@$instances) {

    $instance =~ s/\.sanger\.ac\.uk//;
    $report .= "Opening $instance ...";
    my ($host,$port) = split ':',$instance;
    if ($GateKeeper->ping_MySQL($host,$port)) {
        my $handle   = $GateKeeper->opendb_MySQL_unchecked($instance,{dieOnError => 0});
        print "MySQL instance $instance cannot be opened\n" if !$handle;
        $handles{$instance} = $handle if $handle;
    }
    else {
        print "MySQL instance $instance is not available\n";
    }
    $report .= "... done \n";
}

$report = $GateKeeper->whereAmI();
print $report;

##############################################################################
# MAIN
##############################################################################

undef my %organisms;
foreach my $instance (keys %handles) {
    my $handle = $handles{$instance};
    my $organism = ArcturusTable->new($handle,'ORGANISMS','arcturus',1);
    $organisms{$instance} = $organism if $organism;
}

foreach my $instance (keys %organisms) {
    my $organism = $organisms{$instance};
    print "\n\n$instance \n";
    my $list = $organism->list('111111111111111111111');
    print $list;
}

##############################################################################
# EXIT
##############################################################################

print "closing down\n";

foreach my $instance (keys %handles) {
    $handles{$instance}->disconnect();
}





