#!/usr/local/bin/perl 

#############################################################################
#
# Upload Reads into ARCTURUS database
#
#############################################################################

use strict; # Constraint variables declaration before using them

use GateKeeper; 

##############################################################################
# unbuffered output
##############################################################################

open(STDERR,">&STDOUT") || die "Can't dump to STDOUT: $!\n";
select(STDERR); $| = 1; # Make unbuffered.
select(STDOUT); $| = 1; # Make unbuffered.

##############################################################################
# get configuration data, open CGI and MySQL Database
##############################################################################

my $GateKeeper = new GateKeeper('mysql',0,'insist on CGI');

my $cgi        = $GateKeeper->cgiHandle(1);

my $database   = $cgi->parameter('database') || 'arcturus';

my $organisms  = $GateKeeper->dbHandle($database,{returnTableHandle => 1});

##############################################################################
# MAIN
##############################################################################

my ($void, $action, $page);

($void, $action) = split ('/',$GateKeeper->origin);

if (!$action || $action eq 'signon') {

    $page = $GateKeeper->GUI("Welcome to the assembly-tracking database");

    $page->space;
    $page->sectionheader("Welcome to the ARCTURUS assembly-tracking database",4,0);

    my $count = $organisms->count();
    my $text = "There are $count Organism databases on this server";
    $text =~ s/are/is/ if ($count <= 1);
    $text =~ s/ses/se/ if ($count <= 1);
    $count = 'no' if !$count;  
    $page->add($text,0,0,"size=+1");
    $page->space;

    if ($database ne 'arcturus') {
        my %options = (mask=>'011000001111000001',
                       headColor=>'FAFAD2',cellColor=>'CCCCCC',linkColor=>'E2E2FF');
        my $table = $organisms->htmlTable(\%options,'dbasename',$database);
        $page->add($table);
# possibly other info
    }
    else {
        my %options = (mask=>'031000001111000001',linkItem=>'onItemName', linkTarget=>0,
                       headColor=>'FAFAD2',cellColor=>'CCCCCC',linkColor=>'E2E2FF');
        my $table = $organisms->htmlTable(\%options);
        $table =~ s?ITEMLINK?/cgi-bin/herdsman/signon?; 
        $table =~ s/dbasename/database/g;
        $page->add($table);
        $page->space;
        $page->sectionheader("Select a database or a function",4,0);
    }

    $page->flush();
}
elsif ($action eq 'signoff') {

    $GateKeeper->cgiHeader(2);

}
else {
    $GateKeeper->cgiHeader(1);
}

##############################################################################

$GateKeeper->disconnect;

exit 0;

