#!/usr/local/bin/perl 

#############################################################################
#
# Upload Reads into ARCTURUS database
#
#############################################################################

use strict; # Constraint variables declaration before using them

use GateKeeper; 

##############################################################################
# unbuffered output
##############################################################################

open(STDERR,">&STDOUT") || die "Can't dump to STDOUT: $!\n";
select(STDERR); $| = 1; # Make unbuffered.
select(STDOUT); $| = 1; # Make unbuffered.

##############################################################################
# get configuration data, open CGI and MySQL Database
##############################################################################

my $GateKeeper = new GateKeeper('mysql',{insistOnCGI=>1 , diagnosticsOn=>0});

my $cgi        = $GateKeeper->cgiHandle(1);

my $database   = $cgi->parameter('database') || 'arcturus';

my $organisms  = $GateKeeper->dbHandle($database,{returnTableHandle => 1});

##############################################################################
# MAIN
##############################################################################

my ($void, $action, $page);

($void, $action) = split ('/',$GateKeeper->origin);

if ($action eq 'signon') {

    $page = $GateKeeper->GUI("Welcome to the assembly-tracking database");
    $GateKeeper->authorize(0,{ageWindow=>180}); # bounce authorization form    
}

elsif ($action eq 'signoff') {

    $page = $GateKeeper->GUI("Sign off");
    $GateKeeper->cgiHeader(2);
    $page->add("Your current session will be closed"); 
    $page->flush();

}

else {
# if the script is invoked by the identification prompt: get session number
    if ($cgi->parameter('identify')) {
        $GateKeeper->authorize(0,{ageWindow=>180}); # (no access test)  
    }

    $page = $GateKeeper->GUI("Welcome to the assembly-tracking database");
    $page->space;
    $page->sectionheader("Welcome to the ARCTURUS assembly-tracking database",4,0);

    my $count = $organisms->count();
    my $text = "There are $count Organism databases on this server";
    $text =~ s/are/is/ if ($count <= 1);
    $text =~ s/ses/se/ if ($count <= 1);
    $count = 'no' if !$count;  
    $page->add($text,0,0,"size=+1");
    $page->space;

    if ($database ne 'arcturus') {
        my %options = (mask=>'011000001111000001',
                       headColor=>'FAFAD2',cellColor=>'CCCCCC',linkColor=>'E2E2FF');
        my $table = $organisms->htmlTable(\%options,'dbasename',$database);
        $page->add($table);
# possibly other info
    }
    else {
        my %options = (mask=>'031000001111000001',linkItem=>'onItemName', linkTarget=>0,
                       headColor=>'FAFAD2',cellColor=>'CCCCCC',linkColor=>'E2E2FF');
        my $table = $organisms->htmlTable(\%options);

        my $thisScript = $GateKeeper->currentScript;
        my $session = $cgi->parameter('session');
        $table =~ s/ITEMLINK\?/ITEMLINK?session=$session&/g if $session;
        $table =~ s/ITEMLINK/$thisScript/g;
        $table =~ s/dbasename/database/g;

        $page->add($table);
        $page->space;
        $page->sectionheader("Select a database or a function",4,0);
    }

    $page->flush();
}

##############################################################################

$GateKeeper->disconnect;

exit 0;



