#!/bin/csh -f

set basedir=`dirname $0`

setenv JAVA_HOME /software/jdk1.6.0_01

set JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false"

set TEST_OPTS="-Dtesting=true"
  
if ( $?JAVA_OPTS ) then
  setenv JAVA_OPTS "${JAVA_OPTS} ${JMX_OPTS} ${TEST_OPTS}"
else
  setenv JAVA_OPTS "${JMX_OPTS} ${TEST_OPTS}"
endif

source ${basedir}/setup.csh

${JAVA_HOME}/bin/java ${JAVA_OPTS} -jar ${ARCTURUS_JAR} $*
