#!/bin/csh -f

set HEADLESS="-Djava.awt.headless=true"

set ALLOWDUPLICATES="-Dmappingmanager.allowduplicatesequences=true"

if ( $?JAVA_OPTS) then
  setenv JAVA_OPTS "${JAVA_OPTS} ${HEADLESS} ${ALLOWDUPLICATES}"
else
  setenv JAVA_OPTS "${HEADLESS} ${ALLOWDUPLICATES}"
endif

set basedir=`dirname $0`
source ${basedir}/setup.csh

set ARCTURUS_JAR=${ARCTURUS_HOME}/../arcturus2.jar
echo Arcturus JAR file is $ARCTURUS_JAR

${JAVA_HOME}/bin/java ${JAVA_OPTS} -classpath ${ARCTURUS_JAR} ${ARCTURUS_APPS_PACKAGE}.ContigLoader $*
